version: "3.7"

services:
  nginx:
    image: nginx:latest
    command: python manage.py runserver 0.0.0.0:8000
    container_name: nginx
    volumes:
       - ./app:/
    ports:
      - "80:80"
      - "443:443"
