version: "3.5"

services:
  database:
    image: mariadb
    restart: on-failure
    platform: linux/amd64
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    container_name: database
    ports:
      - "3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: [ "CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]

  nginx:
    image: nginx:latest
    restart: always
    build: ./nginx/
    container_name: nginx
    volumes:
       - ./app:/DjangoTrader/app
       - ./nginx/lemon.army:/etc/letsencrypt/live/lemon.army
       - ./nginx/certbot/conf:/etc/letsencrypt/conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web



  web:
    build: .
    command: sh ./docker-entrypoint.sh
    container_name: web
    environment:
      - MYSQL_SERVER
      - MYSQL_USER
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - REDIS_SERVER
      - REDIS_PASSWORD
    volumes:
      - ./app:/DjangoTrader/app
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    depends_on:
      database:
        condition: service_healthy

  redis:
    restart: always
    image: redis:latest
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/DjangoTrader/data




